# This is a Docker Compose file for local development.
services:

  mkdocs:
    build: .
    environment:
      - ENABLE_PDF_EXPORT=0 # Makes PDF export an option, default disabled for local dev
      - ENABLE_GIT_COMMITTERS=True # Makes git-committers an option, default enabled
    volumes:
      - .:/app
    ports:
      - 8008:8000 # MkDocs will be accessible at localhost:8008
    command: sh -c "mkdocs serve --dev-addr=0.0.0.0:8000"
    restart: unless-stopped